Feature/entities
Nearrivers/kanban-core-lib pull request #2
Opened 2022-11-05 11:18 UTC by Nearrivers

Création des modèles de la base de données.

2022-11-11 11:30 UTC, FrozyPenguin requested changes
À revoir

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +    const errors = await validate(list);
Sur 41,42,43, j'aurais mis le code dans une fonction dédié à la validation qui throw si c'est pas passé et j'aurais fais un expect(fonction).not.toThrow()

2022-11-11 11:30 UTC, FrozyPenguin commented on jest.config.js
> +  preset: 'ts-jest',
Utilise plutôt un fichier ts ou json. Ça éviteras qu'on ait des fichier JS qui se baladent pour rien

2022-11-11 11:30 UTC, FrozyPenguin commented on src/data-access/data-source.ts
> +    logging: process.env.NODE_ENV === Environments.DEVELOPEMENT,
Enlève moi ça fait pas le mettre là

2022-11-11 11:30 UTC, FrozyPenguin commented on src/data-access/data-source.ts
> +    synchronize: true,
Enlève ça

2022-11-11 11:30 UTC, FrozyPenguin commented on src/data-access/data-source.ts
> +import { Environments } from '../config/environments.enum'
Enlève ça et les commentaires aussi

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +    if (errors.length > 0) {
Ça sert a rien vu que si tu arrives à ce point c'est que t'es forcément supérieur à 0

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +    if (errors.length > 0) {
Même commentaire que le test précédent

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que le test précédent

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que le test précédent

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que le test précédent

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/list.spec.ts
> +  // afterAll(async () => {
Pourquoi tu l'as enlevé ?

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +    if (errors.length > 0) {
Même commentaires que pour les test de List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que pour les test de List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que pour les test de List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que pour les test de List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +    if (!(errors.length > 0)) throw new Error();
Même commentaires que pour les test de List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +     WHEN I try to insert a project with a color value over 0xFFFFFFFF
En soit tu testes seulement la validation pas ma réelle insertion en base

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +    await manager.save(project);
Faudrait peut être créer un entity manager custom qui hérite de entity manager et qui override le save pour exécuter la validation directement (enfin peut être qu'il le fait déjà)

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +  // afterAll(async () => {
Pourquoi tu l'as supprimé ?

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/tag.spec.ts
> +import { validate } from 'class-validator';
Globalement les même remarques que sur les tests de l'entity List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/__tests__/user.spec.ts
> +import { validate } from 'class-validator';
Globalement les même remarques que sur les tests de l'entity List

2022-11-11 11:30 UTC, FrozyPenguin commented on src/entities/Project.ts
> +    name: string;
Du coup t'as pas mis le nom en primary ?

2022-11-11 11:30 UTC, FrozyPenguin commented on src/utils/GenericEntity.ts
> +export class GenericEntity {
T'utilises des IDs partout du coup ? Même sur les entities ou le nom est unique ?

2022-11-11 11:30 UTC, FrozyPenguin commented on src/utils/MockConnection.ts
> +  tearDown(): Promise<void> {
Pour une raison ou une autre tu l'utilises plus du tout du coup

2022-11-11 11:45 UTC, Nearrivers commented on src/entities/Project.ts
> +    name: string;
Par habitude de travailler qu'avec des id en primary

2022-11-11 11:50 UTC, Nearrivers commented on src/entities/__tests__/project.spec.ts
> +    await manager.save(project);
C'est justement la prochaine feature que je pensais faire un repository avec toutes les méthodes de CRUD et un service qui fait toutes les validations.

2022-11-11 11:55 UTC, Nearrivers commented on src/entities/__tests__/list.spec.ts
> +    const errors = await validate(list);
`expect(async () => {
      const errors = await validate(list);
      if (!(errors.length > 0)) throw new Error(errors[0].constraints.isLength);
    }).not.toThrow()`
Quelque chose dans ce style ?

2022-11-11 11:56 UTC, Nearrivers commented on src/entities/__tests__/project.spec.ts
> +     WHEN I try to insert a project with a color value over 0xFFFFFFFF
Tu penses que ces tests ne servent à rien ?

2022-11-11 11:56 UTC, Nearrivers commented on src/utils/GenericEntity.ts
> +export class GenericEntity {
Pour l'instant oui mais si tu juges ça dégueulasse on peut changer

2022-11-11 20:08 UTC, FrozyPenguin commented on src/entities/__tests__/project.spec.ts
> +     WHEN I try to insert a project with a color value over 0xFFFFFFFF
Non mais le test est peut être mal nommé du coup

2022-11-11 20:11 UTC, FrozyPenguin commented on src/utils/GenericEntity.ts
> +export class GenericEntity {
Ça dépend de tes choix. Si tu juges ça utile pourquoi pas après si tu veux respecter à la lettre les modèles de conception de bdd ça devient pas pertinent d'utiliser des IDs là où tu as des champs unique qui permettent déjà d'identifier de manière unique une ligne de la table. A toi de voir.

2022-11-17 19:11 UTC, FrozyPenguin approved these changes

2022-11-17 19:12 UTC, merged